export const FETCH_TODO_REQUESTED = 'FETCH_TODO_REQUESTED';
export const FETCH_TODO_SUCCEEDED = 'FETCH_TODO_SUCCEEDED';
export const FETCH_TODO_FAILED = 'FETCH_TODO_FAILED';

export const ADD_TODO_REQUESTED = 'ADD_TODO_REQUESTED';
export const ADD_TODO_SUCCEEDED = 'ADD_TODO_SUCCEEDED';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

export const EDIT_TODO_REQUESTED = 'EDIT_TODO_REQUESTED';
export const EDIT_TODO_SUCCEEDED = 'EDIT_TODO_SUCCEEDED';
export const EDIT_TODO_FAILED = 'EDIT_TODO_FAILED';
